In [1]:
# Imports

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf 
import plotly.express as px
from sklearn import metrics
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.model_selection import train_test_split, KFold
from sklearn.preprocessing import PolynomialFeatures, LabelEncoder, MinMaxScaler
from tensorflow.keras.models import Model
from tensorflow.keras.models import load_model

from forecasting_func import timeSeriesMultivariate, timeSeriesEvaluationMetrics

In [2]:
# Reading CSV dataset with ANSI encoding as it includes German Tokens

df = pd.read_csv(r"dataset/preprocessed_accidents.csv", encoding = "ANSI")
df = df.iloc[:, 1:]
df

               Category        AccidentType  Year   Month  Value
0     Traffic Accidents  injured and killed  2000  200012  515.0
1     Traffic Accidents  injured and killed  2000  200011  578.0
2     Traffic Accidents  injured and killed  2000  200010  615.0
3     Traffic Accidents  injured and killed  2000  200009  675.0
4     Traffic Accidents  injured and killed  2000  200008  647.0
...                 ...                 ...   ...     ...    ...
1759  Alcohol Accidents            subtotal  2020  202005   40.0
1760  Alcohol Accidents            subtotal  2020  202004   26.0
1761  Alcohol Accidents            subtotal  2020  202003   27.0
1762  Alcohol Accidents            subtotal  2020  202002   40.0
1763  Alcohol Accidents            subtotal  2020  202001   28.0

[1764 rows x 5 columns]

In [3]:
len(pd.unique(df['Month']))

252

This means there are 252 uniques dates in this dataset. So we have to iterate every 252 records and mark their respective category and types of deaths

In [4]:
date_vals = {}
for index, row in df.iterrows():
    date_vals[row['Month']] = []
for index, row in df.iterrows():
    date_vals[row['Month']].append(row['Value'])

In [5]:
# for date, vals in date_vals.items():
#     date_vals[date][2] = vals[2] - vals[1] - vals[0]
#     date_vals[date][4] = vals[4] - vals[3]
#     date_vals[date][6] = vals[6] - vals[5]
    
date_vals

{200012: [515.0, 403.0, 3789.0, 45.0, 950.0, 31.0, 85.0],
 200011: [578.0, 461.0, 3931.0, 56.0, 1017.0, 24.0, 71.0],
 200010: [615.0, 493.0, 4117.0, 47.0, 1078.0, 31.0, 83.0],
 200009: [675.0, 557.0, 3807.0, 68.0, 978.0, 45.0, 84.0],
 200008: [647.0, 525.0, 3387.0, 74.0, 881.0, 32.0, 77.0],
 200007: [744.0, 610.0, 4282.0, 67.0, 1102.0, 37.0, 99.0],
 200006: [685.0, 555.0, 3329.0, 58.0, 842.0, 32.0, 57.0],
 200005: [675.0, 568.0, 4123.0, 69.0, 1086.0, 44.0, 96.0],
 200004: [557.0, 441.0, 3317.0, 57.0, 834.0, 26.0, 78.0],
 200003: [509.0, 414.0, 3783.0, 48.0, 974.0, 18.0, 73.0],
 200002: [419.0, 329.0, 3181.0, 35.0, 890.0, 19.0, 53.0],
 200001: [434.0, 321.0, 3448.0, 34.0, 835.0, 37.0, 78.0],
 200112: [507.0, 377.0, 3989.0, 39.0, 941.0, 23.0, 66.0],
 200111: [568.0, 436.0, 4022.0, 32.0, 1001.0, 25.0, 68.0],
 200110: [717.0, 581.0, 4250.0, 85.0, 1104.0, 37.0, 77.0],
 200109: [643.0, 497.0, 3939.0, 40.0, 953.0, 48.0, 107.0],
 200108: [600.0, 510.0, 3351.0, 57.0, 814.0, 21.0, 60.0],
 200107: [921.0, 755.0, 4288.0, 83.0, 1047.0, 35.0, 71.0],
 200106: [679.0, 560.0, 3715.0, 78.0, 905.0, 46.0, 68.0],
 200105: [817.0, 655.0, 4128.0, 67.0, 1081.0, 32.0, 85.0],
 200104: [578.0, 454.0, 3565.0, 68.0, 897.0, 32.0, 68.0],
 200103: [535.0, 426.0, 3970.0, 43.0, 962.0, 36.0, 63.0],
 200102: [439.0, 343.0, 3148.0, 51.0, 820.0, 20.0, 49.0],
 200101: [448.0, 354.0, 3348.0, 44.0, 871.0, 36.0, 66.0],
 200212: [394.0, 304.0, 3023.0, 38.0, 706.0, 27.0, 63.0],
 200211: [563.0, 448.0, 3529.0, 50.0, 882.0, 10.0, 44.0],
 200210: [630.0, 467.0, 3859.0, 49.0, 1019.0, 53.0, 83.0],
 200209: [621.0, 509.0, 3436.0, 77.0, 1039.0, 51.0, 107.0],
 200208: [601.0, 479.0, 3007.0, 50.0, 785.0, 29.0, 71.0],
 200207: [865.0, 711.0, 3960.0, 72.0, 1026.0, 40.0, 84.0],
 200206: [833.0, 675.0, 3586.0, 74.0, 987.0, 42.0, 74.0],
 200205: [654.0, 537.0, 3731.0, 73.0, 857.0, 32.0, 58.0],
 200204: [521.0, 432.0, 3142.0, 37.0, 784.0, 28.0, 65.0],
 200203: [520.0, 414.0, 3380.0, 39.0, 897.0, 21.0, 61.0],
 200202: [393.0, 316.0, 2892.0, 33.0, 817.0, 22.0, 49.0],
 200201: [431.0, 328.0, 3063.0, 36.0, 852.0, 24.0, 44.0],
 200312: [493.0, 383.0, 3527.0, 78.0, 858.0, 27.0, 58.0],
 200311: [464.0, 359.0, 3325.0, 59.0, 953.0, 31.0, 44.0],
 200310: [595.0, 466.0, 3631.0, 47.0, 960.0, 17.0, 74.0],
 200309: [560.0, 452.0, 3393.0, 50.0, 945.0, 26.0, 63.0],
 200308: [577.0, 461.0, 2837.0, 41.0, 698.0, 40.0, 66.0],
 200307: [644.0, 538.0, 3321.0, 35.0, 562.0, 35.0, 76.0],
 200306: [723.0, 566.0, 3139.0, 81.0, 855.0, 41.0, 82.0],
 200305: [632.0, 510.0, 3255.0, 56.0, 763.0, 26.0, 65.0],
 200304: [535.0, 429.0, 3106.0, 30.0, 844.0, 25.0, 50.0],
 200303: [476.0, 374.0, 3060.0, 44.0, 854.0, 17.0, 53.0],
 200302: [308.0, 232.0, 2968.0, 20.0, 572.0, 16.0, 44.0],
 200301: [358.0, 282.0, 3073.0, 21.0, 747.0, 18.0, 55.0],
 200412: [416.0, 416.0, 3792.0, 45.0, 942.0, 12.0, 52.0],
 200411: [439.0, 360.0, 3449.0, 46.0, 903.0, 20.0, 51.0],
 200410: [561.0, 465.0, 3716.0, 40.0, 1022.0, 26.0, 68.0],
 200409: [659.0, 541.0, 3663.0, 63.0, 957.0, 41.0, 79.0],
 200408: [584.0, 584.0, 2926.0, 48.0, 784.0, 47.0, 58.0],
 200407: [811.0, 646.0, 3760.0, 83.0, 970.0, 44.0, 67.0],
 200406: [598.0, 491.0, 3229.0, 53.0, 859.0, 25.0, 58.0],
 200405: [600.0, 476.0, 3378.0, 41.0, 867.0, 30.0, 55.0],
 200404: [461.0, 388.0, 3183.0, 39.0, 875.0, 10.0, 37.0],
 200403: [403.0, 321.0, 3271.0, 20.0, 817.0, 18.0, 44.0],
 200402: [310.0, 240.0, 2728.0, 31.0, 723.0, 21.0, 48.0],
 200401: [377.0, 286.0, 2969.0, 33.0, 828.0, 10.0, 42.0],
 200512: [460.0, 487.0, 3549.0, 32.0, 817.0, 12.0, 41.0],
 200511: [458.0, 496.0, 3205.0, 27.0, 845.0, 14.0, 42.0],
 200510: [568.0, 451.0, 3503.0, 54.0, 962.0, 35.0, 57.0],
 200509: [825.0, 678.0, 3921.0, 81.0, 1086.0, 50.0, 76.0],
 200508: [582.0, 462.0, 2965.0, 37.0, 811.0, 33.0, 48.0],
 200507: [675.0, 558.0, 3631.0, 65.0, 951.0, 26.0, 63.0],
 200506: [729.0, 627.0, 3499.0, 53.0, 901.0, 31.0, 57.0],
 200505: [618.0, 521.0, 3321.0, 52.0, 902.0, 21.0, 48.0],
 200504: [514.0, 422.0, 3320.0, 45.0, 937.0, 19.0, 40.0],
 200503: [385.0, 299.0, 3560.0, 33.0, 1115.0, 13.0, 40.0],
 200502: [282.0, 229.0, 3461.0, 22.0, 961.0, 14.0, 40.0],
 200501: [306.0, 244.0, 2788.0, 24.0, 749.0, 13.0, 48.0],
 200612: [466.0, 386.0, 3419.0, 44.0, 864.0, 21.0, 52.0],
 200611: [468.0, 384.0, 3073.0, 38.0, 494.0, 22.0, 48.0],
 200610: [632.0, 500.0, 3286.0, 43.0, 599.0, 24.0, 45.0],
 200609: [490.0, 407.0, 3233.0, 66.0, 718.0, 35.0, 64.0],
 200608: [513.0, 422.0, 2993.0, 40.0, 774.0, 25.0, 48.0],
 200607: [787.0, 671.0, 3611.0, 78.0, 845.0, 37.0, 64.0],
 200606: [479.0, 406.0, 2853.0, 40.0, 565.0, 22.0, 51.0],
 200605: [564.0, 471.0, 3032.0, 33.0, 476.0, 28.0, 53.0],
 200604: [387.0, 301.0, 2874.0, 25.0, 750.0, 16.0, 40.0],
 200603: [375.0, 275.0, 4165.0, 34.0, 1138.0, 14.0, 40.0],
 200602: [279.0, 237.0, 2901.0, 33.0, 698.0, 21.0, 50.0],
 200601: [364.0, 291.0, 2893.0, 31.0, 708.0, 21.0, 44.0],
 200712: [414.0, 333.0, 3184.0, 29.0, 690.0, 20.0, 37.0],
 200711: [405.0, 324.0, 3444.0, 46.0, 868.0, 26.0, 36.0],
 200710: [491.0, 405.0, 3695.0, 49.0, 873.0, 18.0, 55.0],
 200709: [462.0, 385.0, 3414.0, 41.0, 797.0, 24.0, 54.0],
 200708: [422.0, 344.0, 2943.0, 39.0, 759.0, 20.0, 44.0],
 200707: [511.0, 435.0, 3622.0, 59.0, 935.0, 38.0, 65.0],
 200706: [535.0, 444.0, 3225.0, 50.0, 804.0, 27.0, 51.0],
 200705: [591.0, 482.0, 3529.0, 48.0, 858.0, 39.0, 63.0],
 200704: [500.0, 396.0, 3292.0, 43.0, 821.0, 27.0, 49.0],
 200703: [347.0, 293.0, 2836.0, 20.0, 411.0, 14.0, 38.0],
 200702: [277.0, 217.0, 2643.0, 33.0, 612.0, 15.0, 32.0],
 200701: [268.0, 218.0, 2735.0, 19.0, 699.0, 13.0, 36.0],
 200812: [272.0, 230.0, 2888.0, 27.0, 657.0, 20.0, 35.0],
 200811: [321.0, 281.0, 2983.0, 27.0, 625.0, 14.0, 27.0],
 200810: [455.0, 373.0, 3683.0, 46.0, 874.0, 19.0, 45.0],
 200809: [422.0, 360.0, 3271.0, 48.0, 747.0, 28.0, 49.0],
 200808: [480.0, 402.0, 2870.0, 55.0, 760.0, 23.0, 44.0],
 200807: [538.0, 459.0, 3500.0, 48.0, 832.0, 24.0, 52.0],
 200806: [473.0, 424.0, 3374.0, 59.0, 859.0, 32.0, 56.0],
 200805: [534.0, 445.0, 3428.0, 57.0, 871.0, 37.0, 57.0],
 200804: [355.0, 315.0, 3339.0, 41.0, 837.0, 10.0, 25.0],
 200803: [254.0, 210.0, 2910.0, 25.0, 763.0, 9.0, 30.0],
 200802: [340.0, 279.0, 3171.0, 29.0, 793.0, 16.0, 30.0],
 200801: [307.0, 260.0, 2945.0, 27.0, 727.0, 8.0, 32.0],
 200912: [391.0, 312.0, 3202.0, 37.0, 747.0, 14.0, 34.0],
 200911: [366.0, 312.0, 3294.0, 34.0, 835.0, 5.0, 31.0],
 200910: [432.0, 360.0, 3567.0, 47.0, 953.0, 15.0, 35.0],
 200909: [452.0, 388.0, 3252.0, 37.0, 846.0, 18.0, 49.0],
 200908: [466.0, 376.0, 2749.0, 40.0, 752.0, 26.0, 35.0],
 200907: [556.0, 476.0, 3622.0, 61.0, 991.0, 27.0, 44.0],
 200906: [443.0, 371.0, 2876.0, 34.0, 678.0, 19.0, 31.0],
 200905: [535.0, 454.0, 3240.0, 49.0, 768.0, 34.0, 57.0],
 200904: [416.0, 357.0, 2953.0, 43.0, 776.0, 31.0, 45.0],
 200903: [245.0, 202.0, 2744.0, 20.0, 607.0, 5.0, 14.0],
 200902: [340.0, 273.0, 3480.0, 35.0, 802.0, 12.0, 32.0],
 200901: [223.0, 184.0, 2482.0, 22.0, 512.0, 7.0, 23.0],
 201012: [277.0, 223.0, 3413.0, 23.0, 861.0, 12.0, 26.0],
 201011: [383.0, 319.0, 3329.0, 33.0, 827.0, 7.0, 28.0],
 201010: [524.0, 432.0, 3500.0, 49.0, 910.0, 13.0, 27.0],
 201009: [534.0, 456.0, 3524.0, 42.0, 955.0, 26.0, 54.0],
 201008: [481.0, 416.0, 2843.0, 48.0, 794.0, 25.0, 40.0],
 201007: [721.0, 619.0, 3712.0, 65.0, 932.0, 29.0, 48.0],
 201006: [517.0, 440.0, 3193.0, 57.0, 814.0, 20.0, 39.0],
 201005: [389.0, 320.0, 2974.0, 31.0, 743.0, 15.0, 34.0],
 201004: [216.0, 377.0, 3202.0, 41.0, 938.0, 25.0, 33.0],
 201003: [341.0, 291.0, 3309.0, 29.0, 829.0, 12.0, 31.0],
 201002: [247.0, 200.0, 2539.0, 21.0, 683.0, 10.0, 23.0],
 201001: [192.0, 147.0, 2346.0, 17.0, 613.0, 7.0, 19.0],
 201112: [370.0, 315.0, 3506.0, 30.0, 832.0, 6.0, 37.0],
 201111: [438.0, 359.0, 3567.0, 33.0, 842.0, 16.0, 40.0],
 201110: [481.0, 393.0, 3830.0, 36.0, 916.0, 10.0, 26.0],
 201109: [519.0, 441.0, 3730.0, 52.0, 906.0, 22.0, 36.0],
 201108: [487.0, 402.0, 3322.0, 35.0, 790.0, 17.0, 34.0],
 201107: [637.0, 532.0, 4074.0, 56.0, 951.0, 27.0, 39.0],
 201106: [472.0, 399.0, 3212.0, 49.0, 783.0, 21.0, 27.0],
 201105: [765.0, 636.0, 4143.0, 68.0, 1034.0, 20.0, 43.0],
 201104: [604.0, 505.0, 3529.0, 55.0, 835.0, 27.0, 43.0],
 201103: [425.0, 373.0, 3523.0, 32.0, 883.0, 9.0, 22.0],
 201102: [343.0, 264.0, 2903.0, 26.0, 760.0, 7.0, 25.0],
 201101: [328.0, 255.0, 2775.0, 26.0, 726.0, 16.0, 25.0],
 201212: [317.0, 248.0, 3395.0, 23.0, 810.0, 11.0, 27.0],
 201211: [471.0, 394.0, 3839.0, 49.0, 984.0, 10.0, 30.0],
 201210: [580.0, 477.0, 4146.0, 61.0, 1090.0, 6.0, 32.0],
 201209: [632.0, 532.0, 3962.0, 61.0, 921.0, 24.0, 49.0],
 201208: [635.0, 545.0, 3452.0, 64.0, 887.0, 31.0, 55.0],
 201207: [730.0, 632.0, 4281.0, 64.0, 1045.0, 30.0, 56.0],
 201206: [681.0, 577.0, 4018.0, 61.0, 1041.0, 35.0, 43.0],
 201205: [719.0, 596.0, 4114.0, 64.0, 1035.0, 33.0, 54.0],
 201204: [485.0, 394.0, 3667.0, 37.0, 919.0, 22.0, 34.0],
 201203: [526.0, 424.0, 3739.0, 44.0, 946.0, 5.0, 21.0],
 201202: [290.0, 233.0, 3102.0, 20.0, 714.0, 5.0, 18.0],
 201201: [338.0, 273.0, 3176.0, 32.0, 713.0, 11.0, 21.0],
 201312: [423.0, 356.0, 3764.0, 27.0, 828.0, 10.0, 32.0],
 201311: [483.0, 388.0, 4043.0, 53.0, 939.0, 12.0, 35.0],
 201310: [595.0, 510.0, 4533.0, 53.0, 1074.0, 12.0, 31.0],
 201309: [617.0, 531.0, 4130.0, 53.0, 1000.0, 17.0, 47.0],
 201308: [645.0, 514.0, 3387.0, 36.0, 791.0, 22.0, 39.0],
 201307: [976.0, 812.0, 4641.0, 68.0, 1138.0, 24.0, 42.0],
 201306: [734.0, 580.0, 4284.0, 54.0, 1055.0, 20.0, 37.0],
 201305: [530.0, 454.0, 3703.0, 43.0, 848.0, 21.0, 33.0],
 201304: [523.0, 440.0, 4008.0, 50.0, 1038.0, 5.0, 28.0],
 201303: [350.0, 284.0, 3712.0, 33.0, 906.0, 8.0, 21.0],
 201302: [326.0, 263.0, 3467.0, 22.0, 773.0, 0.0, 15.0],
 201301: [320.0, 254.0, 3316.0, 29.0, 796.0, 2.0, 17.0],
 201412: [413.0, 331.0, 3919.0, 35.0, 830.0, 3.0, 25.0],
 201411: [464.0, 401.0, 3904.0, 42.0, 943.0, 14.0, 42.0],
 201410: [652.0, 529.0, 4251.0, 55.0, 1042.0, 21.0, 36.0],
 201409: [620.0, 534.0, 4137.0, 60.0, 936.0, 18.0, 43.0],
 201408: [517.0, 432.0, 3379.0, 43.0, 802.0, 13.0, 32.0],
 201407: [783.0, 654.0, 4443.0, 62.0, 1029.0, 21.0, 35.0],
 201406: [656.0, 558.0, 3833.0, 58.0, 880.0, 16.0, 31.0],
 201405: [671.0, 536.0, 4346.0, 50.0, 925.0, 19.0, 28.0],
 201404: [549.0, 455.0, 3840.0, 55.0, 946.0, 15.0, 35.0],
 201403: [559.0, 460.0, 4027.0, 46.0, 993.0, 16.0, 37.0],
 201402: [372.0, 309.0, 3315.0, 22.0, 742.0, 7.0, 17.0],
 201401: [412.0, 324.0, 3410.0, 29.0, 778.0, 4.0, 21.0],
 201512: [479.0, 384.0, 3862.0, 38.0, 950.0, 6.0, 27.0],
 201511: [506.0, 430.0, 3992.0, 43.0, 991.0, 11.0, 30.0],
 201510: [569.0, 475.0, 4467.0, 52.0, 1110.0, 12.0, 25.0],
 201509: [614.0, 509.0, 4015.0, 49.0, 1007.0, 25.0, 45.0],
 201508: [546.0, 481.0, 3431.0, 36.0, 864.0, 29.0, 49.0],
 201507: [809.0, 708.0, 4729.0, 65.0, 1176.0, 37.0, 49.0],
 201506: [673.0, 560.0, 3898.0, 54.0, 952.0, 19.0, 39.0],
 201505: [604.0, 487.0, 3915.0, 41.0, 940.0, 30.0, 50.0],
 201504: [598.0, 495.0, 4022.0, 45.0, 966.0, 23.0, 29.0],
 201503: [471.0, 376.0, 3888.0, 49.0, 908.0, 9.0, 23.0],
 201502: [321.0, 262.0, 3090.0, 18.0, 713.0, 3.0, 23.0],
 201501: [334.0, 263.0, 3326.0, 19.0, 781.0, 21.0, 22.0],
 201612: [381.0, 317.0, 3700.0, 35.0, 870.0, 10.0, 20.0],
 201611: [489.0, 402.0, 3998.0, 32.0, 960.0, 7.0, 20.0],
 201610: [559.0, 448.0, 4297.0, 44.0, 1022.0, 11.0, 30.0],
 201609: [759.0, 627.0, 4289.0, 70.0, 958.0, 22.0, 29.0],
 201608: [540.0, 469.0, 3400.0, 70.0, 958.0, 12.0, 34.0],
 201607: [742.0, 623.0, 4478.0, 61.0, 1095.0, 23.0, 35.0],
 201606: [691.0, 592.0, 4260.0, 54.0, 1018.0, 19.0, 30.0],
 201605: [602.0, 502.0, 3833.0, 44.0, 850.0, 17.0, 25.0],
 201604: [545.0, 447.0, 4209.0, 42.0, 998.0, 8.0, 27.0],
 201603: [370.0, 299.0, 3653.0, 41.0, 898.0, 6.0, 20.0],
 201602: [351.0, 305.0, 3383.0, 24.0, 775.0, 3.0, 10.0],
 201601: [380.0, 298.0, 3297.0, 31.0, 777.0, 6.0, 21.0],
 201712: [376.0, 307.0, 3494.0, 33.0, 873.0, 17.0, 42.0],
 201711: [443.0, 373.0, 3809.0, 48.0, 925.0, 13.0, 33.0],
 201710: [572.0, 490.0, 4198.0, 59.0, 1052.0, 16.0, 32.0],
 201709: [546.0, 430.0, 4017.0, 59.0, 1009.0, 22.0, 47.0],
 201708: [504.0, 447.0, 3267.0, 38.0, 831.0, 14.0, 30.0],
 201707: [752.0, 611.0, 4355.0, 65.0, 1064.0, 18.0, 52.0],
 201706: [668.0, 568.0, 3818.0, 54.0, 948.0, 27.0, 41.0],
 201705: [631.0, 545.0, 4314.0, 60.0, 1070.0, 16.0, 29.0],
 201704: [439.0, 365.0, 3533.0, 36.0, 895.0, 10.0, 26.0],
 201703: [486.0, 407.0, 4106.0, 36.0, 1060.0, 15.0, 36.0],
 201702: [334.0, 277.0, 3223.0, 41.0, 846.0, 4.0, 22.0],
 201701: [307.0, 242.0, 3320.0, 22.0, 690.0, 4.0, 19.0],
 201812: [348.0, 282.0, 3550.0, 37.0, 900.0, 6.0, 21.0],
 201811: [485.0, 407.0, 4027.0, 37.0, 929.0, 13.0, 31.0],
 201810: [616.0, 529.0, 4468.0, 60.0, 1127.0, 16.0, 43.0],
 201809: [645.0, 528.0, 4124.0, 59.0, 1102.0, 22.0, 36.0],
 201808: [529.0, 456.0, 3206.0, 39.0, 813.0, 18.0, 40.0],
 201807: [852.0, 714.0, 4547.0, 72.0, 1151.0, 29.0, 51.0],
 201806: [732.0, 622.0, 4284.0, 49.0, 1034.0, 14.0, 39.0],
 201805: [640.0, 528.0, 3953.0, 43.0, 994.0, 23.0, 34.0],
 201804: [619.0, 519.0, 4016.0, 44.0, 1010.0, 8.0, 25.0],
 201803: [383.0, 331.0, 3796.0, 35.0, 954.0, 12.0, 32.0],
 201802: [328.0, 265.0, 3109.0, 40.0, 774.0, 13.0, 24.0],
 201801: [350.0, 290.0, 3328.0, 40.0, 860.0, 8.0, 22.0],
 201912: [378.0, 326.0, 3462.0, 43.0, 925.0, 12.0, 35.0],
 201911: [453.0, 383.0, 3805.0, 41.0, 967.0, 19.0, 29.0],
 201910: [591.0, 500.0, 4348.0, 45.0, 1088.0, 20.0, 45.0],
 201909: [609.0, 533.0, 4042.0, 55.0, 996.0, 20.0, 47.0],
 201908: [532.0, 451.0, 3214.0, 37.0, 820.0, 23.0, 31.0],
 201907: [898.0, 762.0, 4763.0, 81.0, 1187.0, 34.0, 48.0],
 201906: [710.0, 615.0, 3727.0, 61.0, 994.0, 24.0, 40.0],
 201905: [484.0, 416.0, 4046.0, 41.0, 1014.0, 21.0, 39.0],
 201904: [515.0, 426.0, 3781.0, 35.0, 967.0, 18.0, 36.0],
 201903: [427.0, 369.0, 3940.0, 44.0, 1005.0, 22.0, 34.0],
 201902: [345.0, 289.0, 3442.0, 26.0, 883.0, 7.0, 28.0],
 201901: [297.0, 243.0, 3440.0, 32.0, 927.0, 7.0, 22.0],
 202012: [311.0, 270.0, 2661.0, 33.0, 694.0, 9.0, 13.0],
 202011: [348.0, 297.0, 3150.0, 27.0, 864.0, 11.0, 23.0],
 202010: [566.0, 489.0, 3867.0, 50.0, 997.0, 20.0, 34.0],
 202009: [634.0, 555.0, 3659.0, 49.0, 948.0, 24.0, 46.0],
 202008: [563.0, 487.0, 3007.0, 36.0, 735.0, 29.0, 46.0],
 202007: [821.0, 717.0, 4031.0, 58.0, 1010.0, 43.0, 58.0],
 202006: [585.0, 496.0, 3380.0, 49.0, 905.0, 30.0, 49.0],
 202005: [464.0, 416.0, 3193.0, 34.0, 859.0, 26.0, 40.0],
 202004: [363.0, 314.0, 2251.0, 34.0, 607.0, 15.0, 26.0],
 202003: [334.0, 270.0, 2825.0, 33.0, 744.0, 13.0, 27.0],
 202002: [355.0, 306.0, 3271.0, 34.0, 870.0, 19.0, 40.0],
 202001: [360.0, 301.0, 3139.0, 28.0, 791.0, 11.0, 28.0]}

In [6]:
df = pd.DataFrame.from_dict(date_vals, orient = 'index')
df

            0      1       2     3       4     5     6
200012  515.0  403.0  3789.0  45.0   950.0  31.0  85.0
200011  578.0  461.0  3931.0  56.0  1017.0  24.0  71.0
200010  615.0  493.0  4117.0  47.0  1078.0  31.0  83.0
200009  675.0  557.0  3807.0  68.0   978.0  45.0  84.0
200008  647.0  525.0  3387.0  74.0   881.0  32.0  77.0
...       ...    ...     ...   ...     ...   ...   ...
202005  464.0  416.0  3193.0  34.0   859.0  26.0  40.0
202004  363.0  314.0  2251.0  34.0   607.0  15.0  26.0
202003  334.0  270.0  2825.0  33.0   744.0  13.0  27.0
202002  355.0  306.0  3271.0  34.0   870.0  19.0  40.0
202001  360.0  301.0  3139.0  28.0   791.0  11.0  28.0

[252 rows x 7 columns]

In [7]:
df.columns = [
    'traffic_injured_and_killed', 
    'traffic_with_people',
    'traffic_subtotal',
    'escape_injured_and_killed', 
    'escape_subtotal',
    'alcohol_injured_and_killed',
    'alcohol_subtotal'
]

# df.rename(columns = {
#     '0':'traffic_injured_and_killed', 
#     '1':'traffic_with_people',
#     '2':'traffic_other',
#     '3':'escape_injured_and_killed', 
#     '4':'escape_other',
#     '5':'alcohol_injured_and_killed',
#     '6':'alcohol_other'
# }, inplace = True)

In [8]:
df

,traffic_injured_and_killed,traffic_with_people,traffic_subtotal,escape_injured_and_killed,escape_subtotal,alcohol_injured_and_killed,alcohol_subtotal
200012,515.0,403.0,3789.0,45.0,950.0,31.0,85.0
200011,578.0,461.0,3931.0,56.0,1017.0,24.0,71.0
200010,615.0,493.0,4117.0,47.0,1078.0,31.0,83.0
200009,675.0,557.0,3807.0,68.0,978.0,45.0,84.0
200008,647.0,525.0,3387.0,74.0,881.0,32.0,77.0
...,...,...,...,...,...,...,...
202005,464.0,416.0,3193.0,34.0,859.0,26.0,40.0
202004,363.0,314.0,2251.0,34.0,607.0,15.0,26.0
202003,334.0,270.0,2825.0,33.0,744.0,13.0,27.0
202002,355.0,306.0,3271.0,34.0,870.0,19.0,40.0
202001,360.0,301.0,3139.0,28.0,791.0,11.0,28.0

In [10]:
df.to_csv("./dataset/accident_by_date_insgesamt.csv")

In [ ]:
sum(df['traffic_other'])